#https://docs.travis-ci.com/user/for-beginners/
language: minimal

services: docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

# Pre-testing installs
install:
    - echo "nothing needs to be installed"
    
# Scripts to be run such as tests
before_script:
    - echo "no tests"
  
script:
  - docker --version # print the version for logging
  - docker-compose build --parallel # if we have file to use we can include the file and the path or no path. Eg '-f udacity-deployment/docker/docker-compose-build.yaml' 
  
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #the username and password are defined as environment variables in travis repo. more here https://docs.travis-ci.com/user/environment-variables#defining-variables-in-repository-settings
    - docker-compose push
